const MEALS = [
  {
    id: 1,
    name: "Ugali Sukuma",
    emoji: "🌽",
    tags: ["lunch", "supper"],
    desc: "The undisputed king of campus meals. Stiff maize ugali paired with collard greens sautéed in onion and tomato. Cheap, filling, and at every mama mboga near campus.",
    cost: "Ksh 50–80",
    costMin: 50,
    costMax: 80,
    where: "Mama mboga",
    filling: "⭐⭐⭐⭐⭐",
    protein: "Medium"
  },
  {
    id: 2,
    name: "Githeri",
    emoji: "🫘",
    tags: ["lunch", "supper"],
    desc: "Boiled maize and beans — a Kikuyu classic. Cook a big pot on Sunday and it carries you through the week. High carbs, solid protein.",
    cost: "Ksh 30–60",
    costMin: 30,
    costMax: 60,
    where: "Hostel / canteen",
    filling: "⭐⭐⭐⭐⭐",
    protein: "High"
  },
  {
    id: 3,
    name: "Ndengu + Rice",
    emoji: "🍚",
    tags: ["lunch", "supper"],
    desc: "Green grams in a rich tomato-onion base served over white rice. Cooks faster than most legumes, costs very little, and delivers serious protein.",
    cost: "Ksh 50–70",
    costMin: 50,
    costMax: 70,
    where: "Canteen / cook",
    filling: "⭐⭐⭐⭐",
    protein: "High"
  },
  {
    id: 4,
    name: "Beans Stew + Chapati",
    emoji: "🫓",
    tags: ["supper"],
    desc: "Slow-cooked kidney beans in a thick tomato gravy with a warm, layered chapati. The Friday night comrade classic.",
    cost: "Ksh 60–90",
    costMin: 60,
    costMax: 90,
    where: "Hotel nearby",
    filling: "⭐⭐⭐⭐⭐",
    protein: "High"
  },
  {
    id: 5,
    name: "Ugali + Omena",
    emoji: "🐟",
    tags: ["lunch", "supper"],
    desc: "Small lake sardines fried with onions, tomatoes, and chili, paired with ugali. High protein, strongly flavored, and very affordable.",
    cost: "Ksh 50–80",
    costMin: 50,
    costMax: 80,
    where: "Mama mboga",
    filling: "⭐⭐⭐⭐",
    protein: "Very High"
  },
  {
    id: 6,
    name: "Mandazi + Chai",
    emoji: "☕",
    tags: ["breakfast"],
    desc: "Slightly sweet Swahili doughnuts with a strong milky masala chai. The quintessential Kenyan comrade morning ritual.",
    cost: "Ksh 20–40",
    costMin: 20,
    costMax: 40,
    where: "Kiosk / canteen",
    filling: "⭐⭐⭐",
    protein: "Low"
  },
  {
    id: 7,
    name: "Mahindi choma",
    emoji: "🌽",
    tags: ["snack"],
    desc: "Roasted maize on the cob from the vendor at the gate. No cooking, no planning — just Ksh 20–30 and you're sorted between lectures.",
    cost: "Ksh 20–30",
    costMin: 20,
    costMax: 30,
    where: "Gate / roadside",
    filling: "⭐⭐⭐",
    protein: "Low"
  },
  {
    id: 8,
    name: "Samosa",
    emoji: "🥟",
    tags: ["snack"],
    desc: "Crispy fried pastry stuffed with spiced minced meat or vegetables. Available at literally every kiosk and canteen. The ultimate Ksh 10–20 snack.",
    cost: "Ksh 10–20",
    costMin: 10,
    costMax: 20,
    where: "Any kiosk",
    filling: "⭐⭐",
    protein: "Medium"
  },
  {
    id: 9,
    name: "Bhajia",
    emoji: "🍟",
    tags: ["snack"],
    desc: "Spiced potato fritters, golden and crispy. Filling enough to hold you over until supper, and they go perfectly with kachumbari.",
    cost: "Ksh 30–50",
    costMin: 30,
    costMax: 50,
    where: "Mama mboga",
    filling: "⭐⭐⭐",
    protein: "Low"
  },
  {
    id: 10,
    name: "Pilau",
    emoji: "🍛",
    tags: ["lunch", "supper"],
    desc: "Fragrant long-grain rice spiced with cardamom, cumin, cinnamon, and cloves, cooked with meat. A treat meal when the wallet allows.",
    cost: "Ksh 80–130",
    costMin: 80,
    costMax: 130,
    where: "Hotel / canteen",
    filling: "⭐⭐⭐⭐⭐",
    protein: "High"
  },
  {
    id: 11,
    name: "Mukimo",
    emoji: "🥔",
    tags: ["lunch", "supper"],
    desc: "Mashed potatoes combined with green peas, maize, and greens. A Central Kenya comfort dish — hearty and nutritious.",
    cost: "Ksh 60–90",
    costMin: 60,
    costMax: 90,
    where: "Canteen",
    filling: "⭐⭐⭐⭐⭐",
    protein: "Medium"
  },
  {
    id: 12,
    name: "Uji pawa",
    emoji: "🥣",
    tags: ["breakfast"],
    desc: "Fermented millet porridge — warm, slightly sour, and incredibly energizing. Keeps you sharp through morning lectures.",
    cost: "Ksh 20–40",
    costMin: 20,
    costMax: 40,
    where: "Canteen / hostel",
    filling: "⭐⭐⭐",
    protein: "Medium"
  },
  {
    id: 13,
    name: "Kuku + Ugali",
    emoji: "🍗",
    tags: ["supper"],
    desc: "Chicken stew in a rich tomato-onion base with ugali. The Friday/weekend treat — you've hustled all week, you deserve it.",
    cost: "Ksh 150–200",
    costMin: 150,
    costMax: 200,
    where: "Hotel nearby",
    filling: "⭐⭐⭐⭐⭐",
    protein: "Very High"
  },
  {
    id: 14,
    name: "Viazi Karai",
    emoji: "🥔",
    tags: ["snack"],
    desc: "Battered fried potatoes served with tamarind sauce. A Mombasa coastal export that Nairobi comrades have fully adopted.",
    cost: "Ksh 30–50",
    costMin: 30,
    costMax: 50,
    where: "Street vendor",
    filling: "⭐⭐⭐",
    protein: "Low"
  },
  {
    id: 15,
    name: "Chapati + Tea",
    emoji: "🫓",
    tags: ["breakfast"],
    desc: "A soft layered chapati with a cup of strong milk tea. Simple, warm, and gets the day going without draining the wallet.",
    cost: "Ksh 30–50",
    costMin: 30,
    costMax: 50,
    where: "Canteen / kiosk",
    filling: "⭐⭐⭐",
    protein: "Low"
  },
  {
    id: 16,
    name: "Rice + Beef Stew",
    emoji: "🍖",
    tags: ["lunch", "supper"],
    desc: "Plain white rice with a tomato-based beef stew. Reliable, widely available, and satisfying after a long day of classes.",
    cost: "Ksh 80–120",
    costMin: 80,
    costMax: 120,
    where: "Canteen / hotel",
    filling: "⭐⭐⭐⭐",
    protein: "High"
  },
  {
    id: 17,
    name: "Mutura",
    emoji: "🌭",
    tags: ["snack"],
    desc: "Kenyan meat sausage roasted on charcoal and sold in chunks. A bold, smoky street food popular around Nairobi at dusk.",
    cost: "Ksh 20–50",
    costMin: 20,
    costMax: 50,
    where: "Street vendor",
    filling: "⭐⭐⭐",
    protein: "High"
  },
  {
    id: 18,
    name: "Nyama Choma + Kachumbari",
    emoji: "🥩",
    tags: ["supper"],
    desc: "Roasted goat or beef served with fresh kachumbari — diced tomato, onion, and chili. The social meal of choice. Best shared with comrades.",
    cost: "Ksh 200–400",
    costMin: 200,
    costMax: 400,
    where: "Choma joint",
    filling: "⭐⭐⭐⭐⭐",
    protein: "Very High"
  },
  {
    id: 19,
    name: "Smocha",
    emoji: "🌭",
    tags: ["snacks"],
    desc: "Smokie rolled kwa chapo with fresh kachumbari",
    cost: "Ksh 60",
    costMin: "60",
    costMax: "80",
    where: "roadside",
    filling: "⭐⭐⭐⭐",
    protein: "medium"
  },
  {
    id: 20,
    name: "Ugali mayai",
    emoji: "🌽",
    tags: ["lunch", "supper"],
    desc: "The undisputed king of campus meals. Stiff maize ugali paired with eggs sautéed in onion and tomato. Cheap, filling, and at every mama mboga near campus.",
    cost: "Ksh 50–80",
    costMin: 50,
    costMax: 80,
    where: "Mama mboga",
    filling: "⭐⭐⭐⭐⭐",
    protein: "Medium"
  }
];
