const MEALS = [
  {
    id: 1,
    name: "Ugali Sukuma",
    emoji: "🌽",
    tags: ["lunch", "supper"],
    desc: "The undisputed king of campus meals. Stiff maize ugali paired with collard greens sautéed in onion and tomato. Cheap, filling, and at every mama mboga near campus.",
    cost: "Ksh 50–80",
    costMin: 50,
    costMax: 80,
    where: "Mama mboga",
    filling: "⭐⭐⭐⭐⭐",
    protein: "Medium"
  },
  {
    id: 2,
    name: "Githeri",
    emoji: "🫘",
    tags: ["lunch", "supper"],
    desc: "Boiled maize and beans — a Kikuyu classic. Cook a big pot on Sunday and it carries you through the week. High carbs, solid protein.",
    cost: "Ksh 30–60",
    costMin: 30,
    costMax: 60,
    where: "Hostel / canteen",
    filling: "⭐⭐⭐⭐⭐",
    protein: "High"
  },
  {
    id: 3,
    name: "Ndengu + Rice",
    emoji: "🍚",
    tags: ["lunch", "supper"],
    desc: "Green grams in a rich tomato-onion base served over white rice. Cooks faster than most legumes, costs very little, and delivers serious protein.",
    cost: "Ksh 50–70",
    costMin: 50,
    costMax: 70,
    where: "Canteen / cook",
    filling: "⭐⭐⭐⭐",
    protein: "High"
  },
  {
    id: 4,
    name: "Beans Stew + Chapati",
    emoji: "🫓",
    tags: ["supper"],
    desc: "Slow-cooked kidney beans in a thick tomato gravy with a warm, layered chapati. The Friday night comrade classic.",
    cost: "Ksh 60–90",
    costMin: 60,
    costMax: 90,
    where: "Hotel nearby",
    filling: "⭐⭐⭐⭐⭐",
    protein: "High"
  },
  {
    id: 5,
    name: "Ugali + Omena",
    emoji: "🐟",
    tags: ["lunch", "supper"],
    desc: "Small lake sardines fried with onions, tomatoes, and chili, paired with ugali. High protein, strongly flavored, and very affordable.",
    cost: "Ksh 50–80",
    costMin: 50,
    costMax: 80,
    where: "Mama mboga",
    filling: "⭐⭐⭐⭐",
    protein: "Very High"
  },
  {
    id: 6,
    name: "Mandazi + Chai",
    emoji: "☕",
    tags: ["breakfast"],
    desc: "Slightly sweet Swahili doughnuts with a strong milky masala chai. The quintessential Kenyan comrade morning ritual.",
    cost: "Ksh 20–40",
    costMin: 20,
    costMax: 40,
    where: "Kiosk / canteen",
    filling: "⭐⭐⭐",
    protein: "Low"
  },
  {
    id: 7,
    name: "Mahindi Choma",
    emoji: "🌽",
    tags: ["snack"],
    desc: "Roasted maize on the cob from the vendor at the gate. No cooking, no planning — just Ksh 20–30 and you're sorted between lectures.",
    cost: "Ksh 20–30",
    costMin: 20,
    costMax: 30,
    where: "Gate / roadside",
    filling: "⭐⭐⭐",
    protein: "Low"
  },
  {
    id: 8,
    name: "Samosa",
    emoji: "🥟",
    tags: ["snack"],
    desc: "Crispy fried pastry stuffed with spiced minced meat or vegetables. Available at literally every kiosk and canteen. The ultimate Ksh 10–20 snack.",
    cost: "Ksh 10–20",
    costMin: 10,
    costMax: 20,
    where: "Any kiosk",
    filling: "⭐⭐",
    protein: "Medium"
  },
  {
    id: 9,
    name: "Bhajia",
    emoji: "🍟",
    tags: ["snack"],
    desc: "Spiced potato fritters, golden and crispy. Filling enough to hold you over until supper, and they go perfectly with kachumbari.",
    cost: "Ksh 30–50",
    costMin: 30,
    costMax: 50,
    where: "Mama mboga",
    filling: "⭐⭐⭐",
    protein: "Low"
  },
  {
    id: 10,
    name: "Pilau",
    emoji: "🍛",
    tags: ["lunch", "supper"],
    desc: "Fragrant long-grain rice spiced with cardamom, cumin, cinnamon, and cloves, cooked with meat. A treat meal when the wallet allows.",
    cost: "Ksh 80–130",
    costMin: 80,
    costMax: 130,
    where: "Hotel / canteen",
    filling: "⭐⭐⭐⭐⭐",
    protein: "High"
  },
  {
    id: 11,
    name: "Mukimo",
    emoji: "🥔",
    tags: ["lunch", "supper"],
    desc: "Mashed potatoes combined with green peas, maize, and greens. A Central Kenya comfort dish — hearty and nutritious.",
    cost: "Ksh 60–90",
    costMin: 60,
    costMax: 90,
    where: "Canteen",
    filling: "⭐⭐⭐⭐⭐",
    protein: "Medium"
  },
  {
    id: 12,
    name: "Uji Pawa",
    emoji: "🥣",
    tags: ["breakfast"],
    desc: "Fermented millet porridge — warm, slightly sour, and incredibly energizing. Keeps you sharp through morning lectures.",
    cost: "Ksh 20–40",
    costMin: 20,
    costMax: 40,
    where: "Canteen / hostel",
    filling: "⭐⭐⭐",
    protein: "Medium"
  },
  {
    id: 13,
    name: "Kuku + Ugali",
    emoji: "🍗",
    tags: ["supper"],
    desc: "Chicken stew in a rich tomato-onion base with ugali. The Friday/weekend treat — you've hustled all week, you deserve it.",
    cost: "Ksh 150–200",
    costMin: 150,
    costMax: 200,
    where: "Hotel nearby",
    filling: "⭐⭐⭐⭐⭐",
    protein: "Very High"
  },
  {
    id: 14,
    name: "Viazi Karai",
    emoji: "🥔",
    tags: ["snack"],
    desc: "Battered fried potatoes served with tamarind sauce. A Mombasa coastal export that Nairobi comrades have fully adopted.",
    cost: "Ksh 30–50",
    costMin: 30,
    costMax: 50,
    where: "Street vendor",
    filling: "⭐⭐⭐",
    protein: "Low"
  },
  {
    id: 15,
    name: "Chapati + Tea",
    emoji: "🫓",
    tags: ["breakfast"],
    desc: "A soft layered chapati with a cup of strong milk tea. Simple, warm, and gets the day going without draining the wallet.",
    cost: "Ksh 30–50",
    costMin: 30,
    costMax: 50,
    where: "Canteen / kiosk",
    filling: "⭐⭐⭐",
    protein: "Low"
  },
  {
    id: 16,
    name: "Rice + Beef Stew",
    emoji: "🍖",
    tags: ["lunch", "supper"],
    desc: "Plain white rice with a tomato-based beef stew. Reliable, widely available, and satisfying after a long day of classes.",
    cost: "Ksh 80–120",
    costMin: 80,
    costMax: 120,
    where: "Canteen / hotel",
    filling: "⭐⭐⭐⭐",
    protein: "High"
  },
  {
    id: 17,
    name: "Mutura",
    emoji: "🌭",
    tags: ["snack"],
    desc: "Kenyan meat sausage roasted on charcoal and sold in chunks. A bold, smoky street food popular around Nairobi at dusk.",
    cost: "Ksh 20–50",
    costMin: 20,
    costMax: 50,
    where: "Street vendor",
    filling: "⭐⭐⭐",
    protein: "High"
  },
  {
    id: 18,
    name: "Nyama Choma + Kachumbari",
    emoji: "🥩",
    tags: ["supper"],
    desc: "Roasted goat or beef served with fresh kachumbari — diced tomato, onion, and chili. The social meal of choice. Best shared with comrades.",
    cost: "Ksh 200–400",
    costMin: 200,
    costMax: 400,
    where: "Choma joint",
    filling: "⭐⭐⭐⭐⭐",
    protein: "Very High"
  },
  {
    id: 19,
    name: "Smocha",
    emoji: "🌭",
    tags: ["snack"],
    desc: "Smokie rolled in a chapati with fresh kachumbari and chili sauce. The definitive Nairobi street snack — messy, bold, and worth every shilling.",
    cost: "Ksh 60–80",
    costMin: 60,
    costMax: 80,
    where: "Roadside vendor",
    filling: "⭐⭐⭐⭐",
    protein: "Medium"
  },
  {
    id: 20,
    name: "Ugali Mayai",
    emoji: "🍳",
    tags: ["lunch", "supper"],
    desc: "Ugali paired with scrambled eggs sautéed in onion and tomato. Simple, protein-packed, and easy to find at any mama mboga.",
    cost: "Ksh 50–80",
    costMin: 50,
    costMax: 80,
    where: "Mama mboga",
    filling: "⭐⭐⭐⭐⭐",
    protein: "High"
  },
  {
    id: 21,
    name: "Mkate wa Kumimina",
    emoji: "🍞",
    tags: ["breakfast"],
    desc: "Swahili rice bread — spongy, slightly sweet, and best eaten warm. A coastal breakfast that comrades in Nairobi are slowly discovering.",
    cost: "Ksh 20–40",
    costMin: 20,
    costMax: 40,
    where: "Swahili kiosk",
    filling: "⭐⭐⭐",
    protein: "Low"
  },
  {
    id: 22,
    name: "Eggs + Bread",
    emoji: "🍳",
    tags: ["breakfast"],
    desc: "Fried eggs with sliced white bread — the fastest, cheapest hot breakfast a comrade can put together in a hostel kitchen.",
    cost: "Ksh 30–50",
    costMin: 30,
    costMax: 50,
    where: "Hostel / kiosk",
    filling: "⭐⭐⭐",
    protein: "High"
  },
  {
    id: 23,
    name: "Mahamri + Chai",
    emoji: "🫓",
    tags: ["breakfast"],
    desc: "Coconut and cardamom-spiced fried bread from the coast. Slightly crispy outside, fluffy inside — pairs perfectly with spiced chai.",
    cost: "Ksh 30–50",
    costMin: 30,
    costMax: 50,
    where: "Swahili kiosk",
    filling: "⭐⭐⭐",
    protein: "Low"
  },
  {
    id: 24,
    name: "Viazi + Mayai (Boilo)",
    emoji: "🥚",
    tags: ["snack"],
    desc: "Boiled potatoes and eggs sold in a paper bag at the gate. The ultimate cheap, wholesome snack between classes — filling and zero prep.",
    cost: "Ksh 20–40",
    costMin: 20,
    costMax: 40,
    where: "Gate vendor",
    filling: "⭐⭐⭐",
    protein: "High"
  },
  {
    id: 25,
    name: "Mkate + Blueband",
    emoji: "🍞",
    tags: ["breakfast", "snack"],
    desc: "Sliced bread with Blue Band margarine. The emergency comrade meal when funds are critically low. No judgment — we've all been there.",
    cost: "Ksh 10–20",
    costMin: 10,
    costMax: 20,
    where: "Any kiosk",
    filling: "⭐⭐",
    protein: "Low"
  },
  {
    id: 26,
    name: "Sausage + Chips",
    emoji: "🍟",
    tags: ["lunch", "snack"],
    desc: "Deep-fried chips with a grilled sausage — the campus fast food. Not the healthiest pick but it hits different after a long morning of stats.",
    cost: "Ksh 80–120",
    costMin: 80,
    costMax: 120,
    where: "Canteen / kiosk",
    filling: "⭐⭐⭐⭐",
    protein: "Medium"
  },
  {
    id: 27,
    name: "Groundnuts (Njugu)",
    emoji: "🥜",
    tags: ["snack"],
    desc: "Roasted groundnuts in a small paper cone. Ksh 10 buys you enough to last through a full lecture. The comrade's pocket snack.",
    cost: "Ksh 10–30",
    costMin: 10,
    costMax: 30,
    where: "Any vendor",
    filling: "⭐⭐",
    protein: "High"
  },
  {
    id: 28,
    name: "Mkate wa Soda + Juice",
    emoji: "🧃",
    tags: ["snack"],
    desc: "A scone or soda bread with a packet of juice — the classic tuck shop combo that never fails between 10am and noon.",
    cost: "Ksh 20–40",
    costMin: 20,
    costMax: 40,
    where: "Tuck shop",
    filling: "⭐⭐",
    protein: "Low"
  },
  {
    id: 29,
    name: "Biryani",
    emoji: "🍛",
    tags: ["lunch", "supper"],
    desc: "Layered spiced rice with tender meat, slow-cooked with saffron and whole spices. A Mombasa staple that shows up in Nairobi hotels on good days.",
    cost: "Ksh 120–180",
    costMin: 120,
    costMax: 180,
    where: "Hotel / canteen",
    filling: "⭐⭐⭐⭐⭐",
    protein: "High"
  },
  {
    id: 30,
    name: "Matumbo + Ugali",
    emoji: "🥩",
    tags: ["lunch", "supper"],
    desc: "Tripe stew slow-cooked with tomatoes, onions, and spices. An acquired taste and an extreme budget meal — very filling, very affordable.",
    cost: "Ksh 50–80",
    costMin: 50,
    costMax: 80,
    where: "Mama mboga",
    filling: "⭐⭐⭐⭐⭐",
    protein: "Very High"
  }
];